### PR TITLE
Limit number of createHistoryStream requests during legacy replication

### PR DESCRIPTION
**Pull request by mplorentz**
My database got stuck (see #789) and while I was trying to diagnose it I tried limiting the number of goroutines we use to do createHistoryStream requests during legacy replication.

The old behavior was to spawn one goroutine per feed in the want list for each connected peer. For me this was 6000 * ~4 so about 24k goroutines. This reduces it to ~40 goroutines and doesn't seem to have a very negative impact on replication performance. It also greatly reduces the CPU usage on my phone.

I think I messed up the error handling so this probably needs some further edits. Feel free to push changes to this PR and merge it next week if you want to @boreq.

### CODE REVIEW

**Comment by mplorentz** [comment]
Nvm, I see this has basically already been implemented using `WithNumberOfConcurrentReplicationsPerPeer`. Looks like I turned that off in https://github.com/planetary-social/planetary-ios/pull/608 because it was slowing down full resyncs.

**Comment by rabble** [comment]
i think this is worth doing, we rarely have full re-sync's and we OFTEN have folks with incremental feeds... Maybe make it 80 goroutines or 160... instead of 40, but not the big 6000...

**Comment by boreq** [comment]
Hold on, this PR is incorrect. This is now controlled by setting options named `WithNumberOfConcurrentReplicationsPerPeer` and  `WithNumberOfConcurrentReplications`. Note that `WithNumberOfConcurrentReplicationsPerPeer <= WithNumberOfConcurrentReplications`.

**Comment by mplorentz** [comment]
Whoops, my bad. I think I wrote this on a really old commit.

**Pull request closed without merging**
